name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Запуск каждый день в 00:00 UTC
  workflow_dispatch: # Позволяет запускать вручную

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозиторий
        uses: actions/checkout@v4

      - name: Генерация змейки
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: Commit и Push результата
        run: |
          git config --global vadimvatsenko "github-actions"
          git config --global vadim.vatsenko@gmail.com "github-actions@github.com"
          git add dist/snake.svg
          git commit -m "Обновлена змейка [skip ci]" || exit 0
          git push
