name: Generate snake

on:
  schedule:
    - cron: "0 0 * * *"   # раз в день в 00:00 UTC (на Киеве это ~03:00)
  workflow_dispatch:       # ручной запуск из вкладки Actions

permissions:
  contents: write          # нужно, чтобы пушить файлы в ветку output

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      # 1) Генерируем SVG (и тёмную тему) из твоей contribution-таблицы
      - name: Generate snake SVGs
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: vadimvatsenko
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 2) Публикуем сгенерированные файлы в ветку output
      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
